lang: ru-RU
encoding: utf-8

author: "xenidev"
image: /img/278-289.jpg

exclude:
- README.md



permalink: /notes/:year/:month/:day/:categories/:title
markdown: kramdown
kramdown:
auto_ids: true




gems:
- jekyll-paginate
- jekyll-feed

excerpt_separator: "<!--more-->"
