lang: ru-RU
encoding: utf-8
author: "xenidev"
exclude:
- README.md
permalink: /notes/:year/:month/:day/:categories/:title
markdown: kramdown
kramdown:
auto_ids: true

gems:
- jekyll-paginate
- jekyll-feed

categories: [медтех, разработка, видео]
excerpt_separator: "<!--more-->"
